### ISSUE TITLE
V-Shuttle-M make -j8 error

### ISSUE THREAD

**Issue by painsAgains** [hustdebug/v-shuttle#8]
when I  **compile qemu**  and do `make -j8`, I got the following error

![image](https://user-images.githubusercontent.com/49607803/167242500-e21ca39a-2a6e-4fe1-a91f-f9ec6ea67371.png)

And I check the head file according to the error message,I can't find the wrong place.Is that my gcc's version problem? My gcc version is (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by bob81135** [comment]
Sorry, I also encountered the same problem in the make -j8, I would like to ask how you fixed it, thank you.

**Comment by painsAgains** [comment]
Oh,sorry.It passed a long time,I can't remember the details. I just remember that the problem is related to the gcc version.
 Hope this can help you

**Comment by bob81135** [comment]
I changed the gcc version and it compiles normally. Thank you.

**Comment by painsAgains** [comment]
Not a big deal,I'm glad to help you.Could you tell me your gcc version if you don't mind.Thank you

**Comment by bob81135** [comment]
I am using ubuntu 18.04 and gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0. Thank you.
